export enum PrimaryDiscipline {
  AgriculturalScience = "Agricultural Science",
  Anthropology = "Anthropology",
  Biology = "Biology",
  Chemistry = "Chemistry",
  ComputerScience = "Computer Science",
  Design = "Design",
  Economics = "Economics",
  Education = "Education",
  Engineering = "Engineering",
  EntertainmentandArts = "Entertainment and Arts",
  Geoscience = "Geoscience",
  History = "History",
  Law = "Law",
  Linguistics = "Linguistics",
  Literature = "Literature",
  Mathematics = "Mathematics",
  Medicine = "Medicine",
  Philosophy = "Philosophy",
  Physics = "Physics",
  PoliticalScience = "Political Science",
  Psychology = "Psychology",
  ReligiousStudies = "Religious Studies",
  SocialScience = "Social Science",
  SpaceScience = "Space Science",
}
export enum AgriculturalScienceSubDisciplines {
  AgriculturalEconomics = "Agricultural Economics",
  AgriculturalPhilosophy = "Agricultural Philosophy",
  AgriculturalPlantScience = "Agricultural Plant Science",
  Agronomy = "Agronomy",
  Agrophysics = "Agrophysics",
  AnimalandHumanNutrition = "Animal and Human Nutrition",
  AnimalHealth = "Animal Health",
  AnimalScience = "Animal Science",
  Aquaculture = "Aquaculture",
  EnvironmentalScience = "Environmental Science",
  FoodScience = "Food Science",
  Forestry = "Forestry",
  Horticulture = "Horticulture",
  IrrigationandWaterManagement = "Irrigation and Water Management",
  PlantFertilization = "Plant Fertilization",
  PlantProtection = "Plant Protection",
  SoilScience = "Soil Science",
  TheoreticalProductionEcology = "Theoretical Production Ecology",
  WasteManagement = "Waste Management",
  WaterScience = "Water Science",
}

export enum AnthropologySubDisciplines {
  AnthropologicalLinguistics = "Anthropological Linguistics",
  Archaeology = "Archaeology",
  BiologicalAnthropology = "Biological Anthropology",
  CulturalAnthropology = "Cultural Anthropology",
  HistoricalAnthropology = "Historical Anthropology",
  MedicalAnthropology = "Medical Anthropology",
}

export enum BiologySubDisciplines {
  Aerobiology = "Aerobiology",
  Anatomy = "Anatomy",
  AnimalCommunications = "Animal Communications",
  Bioinformatics = "Bioinformatics",
  Biostatistics = "Biostatistics",
  Biotechnology = "Biotechnology",
  Botany = "Botany",
  CancerResearch = "Cancer Research",
  CanopyResearch = "Canopy Research",
  CellBiology = "Cell Biology",
  Chronobiology = "Chronobiology",
  Cryobiology = "Cryobiology",
  DevelopmentalBiology = "Developmental Biology",
  Ecology = "Ecology",
  Endocrinology = "Endocrinology",
  Entomology = "Entomology",
  Ethnobotany = "Ethnobotany",
  EvolutionaryBiology = "Evolutionary Biology",
  Genetics = "Genetics",
  Histology = "Histology",
  HumanBiology = "Human Biology",
  Immunology = "Immunology",
  Limnology = "Limnology",
  LinnaeanTaxonomy = "Linnaean Taxonomy",
  MarineBiology = "Marine Biology",
  Microbiology = "Microbiology",
  MolecularBiology = "Molecular Biology",
  Mycology = "Mycology",
  Neuroscience = "Neuroscience",
  Paleobiology = "Paleobiology",
  Parasitology = "Parasitology",
  Phycology = "Phycology",
  Physiology = "Physiology",
  StructuralBiology = "Structural Biology",
  Systematics = "Systematics (Taxonomy)",
  SystemsBiology = "Systems Biology",
  Virology = "Virology",
  Xenobiology = "Xenobiology",
  Zoology = "Zoology",
}

export enum ChemistrySubDisciplines {
  AnalyticalChemistry = "Analytical Chemistry",
  Astrochemistry = "Astrochemistry",
  AtmosphericChemistry = "Atmospheric Chemistry",
  Biochemistry = "Biochemistry",
  Catalysis = "Catalysis",
  ChemicalBiology = "Chemical Biology",
  ChemicalKinetics = "Chemical Kinetics",
  ChemicalThermodynamics = "Chemical Thermodynamics",
  Electrochemistry = "Electrochemistry",
  EnvironmentalChemistry = "Environmental Chemistry",
  FlowChemistry = "Flow Chemistry",
  GreenChemistry = "Green Chemistry",
  Immunochemistry = "Immunochemistry",
  InorganicChemistry = "Inorganic Chemistry",
  MaterialsChemistry = "Materials Chemistry",
  MathematicalChemistry = "Mathematical Chemistry",
  MedicinalChemistry = "Medicinal Chemistry",
  Nanobiochemistry = "Nanobiochemistry",
  Nanotechnology = "Nanotechnology",
  NuclearChemistry = "Nuclear Chemistry",
  Oenology = "Oenology",
  OrganicChemistry = "Organic Chemistry",
  OrganometallicChemistry = "Organometallic Chemistry",
  Petrochemistry = "Petrochemistry",
  Pharmacology = "Pharmacology",
  Photochemistry = "Photochemistry",
  PhysicalChemistry = "Physical Chemistry",
  Phytochemistry = "Phytochemistry",
  PolymerChemistry = "Polymer Chemistry",
  Radiochemistry = "Radiochemistry",
  Sonochemistry = "Sonochemistry",
  Spectroscopy = "Spectroscopy",
  SupramolecularChemistry = "Supramolecular Chemistry",
  SurfaceChemistry = "Surface Chemistry",
  TheoreticalChemistry = "Theoretical Chemistry",
  Thermochemistry = "Thermochemistry",
  ChemoInformatics = "Chemo-informatics",
  SolidStateChemistry = "Solid State Chemistry",
}

export enum ComputerScienceSubDisciplines {
  Algorithms = "Algorithms",
  ArtificialIntelligence = "Artificial Intelligence",
  ArtificialNeuralNetwork = "Artificial Neural Network",
  ComputerandSociety = "Computer and Society",
  ComputerArchitecture = "Computer Architecture",
  ComputerSecurityandReliability = "Computer Security and Reliability",
  ComputinginMathematicsNaturalScienceEngineeringandMedicine = "Computing in Mathematics, Natural Science, Engineering and Medicine",
  ComputinginSocialScienceArtsandHumanities = "Computing in Social Science, Arts and Humanities",
  ComputerCommunications = "Computer Communications (Networks)",
  ComputerGraphics = "Computer Graphics",
  DataMining = "Data Mining",
  DataStructures = "Data Structures",
  Databases = "Databases",
  DistributedComputing = "Distributed Computing",
  InformationScience = "Information Science",
  InformationSystems = "Information Systems",
  OperatingSystems = "Operating Systems",
  ParallelComputing = "Parallel Computing",
  ProgrammingLanguages = "Programming Languages",
  QuantumComputing = "Quantum Computing",
  SoftwareEngineering = "Software Engineering",
  TheoryofComputation = "Theory of Computation",
  HumanComputerInteraction = "Human-computer Interaction",
}

export enum DesignSubDisciplines {
  FashionDesign = "Fashion Design",
  GraphicDesign = "Graphic Design",
  IndustrialDesign = "Industrial Design",
}

export enum EconomicsSubDisciplines {
  AccountingScholarship = "Accounting Scholarship",
  BehaviouralEconomics = "Behavioural Economics",
  Bioeconomics = "Bioeconomics",
  BusinessAdministration = "Business Administration",
  BusinessEconomics = "Business Economics",
  BusinessEthics = "Business Ethics",
  CollectiveBargaining = "Collective Bargaining",
  ComputationalEconomics = "Computational Economics",
  ConsumerEconomics = "Consumer Economics",
  DevelopmentEconomics = "Development Economics",
  Econometrics = "Econometrics",
  EconomicGeography = "Economic Geography",
  EconomicHistory = "Economic History",
  EconomicSociology = "Economic Sociology",
  EnergyEconomics = "Energy Economics",
  EntrepreneurialEconomics = "Entrepreneurial Economics",
  EnvironmentalEconomics = "Environmental Economics",
  EvolutionaryEconomics = "Evolutionary Economics",
  ExperimentalEconomics = "Experimental Economics",
  FeministEconomics = "Feminist Economics",
  FinancialEconomics = "Financial Economics",
  GreenEconomics = "Green Economics",
  HealthEconomics = "Health Economics",
  HumanDevelopmentTheory = "Human Development Theory",
  HumanResources = "Human Resources",
  IndustrialOrganization = "Industrial Organization",
  InformationSystems = "Information Systems",
  InstitutionalEconomics = "Institutional Economics",
  InternationalandComparativeLabor = "International and Comparative Labor",
  InternationalEconomics = "International Economics",
  IslamicEconomics = "Islamic Economics",
  LaborEconomics = "Labor Economics",
  LaborHistory = "Labor History",
  LaborStatistics = "Labor Statistics",
  LawandEconomics = "Law and Economics",
  Macroeconomics = "Macroeconomics",
  ManagerialEconomics = "Managerial Economics",
  Manufacturing = "Manufacturing",
  Marketing = "Marketing",
  MathematicalEconomics = "Mathematical Economics",
  Microeconomics = "Microeconomics",
  MonetaryEconomics = "Monetary Economics",
  Neuroeconomics = "Neuroeconomics",
  OrganizationalStudies = "Organizational Studies",
  PlatformEconomics = "Platform Economics",
  PortManagement = "Port Management",
  PublicEconomics = "Public Economics",
  PublicFinance = "Public Finance",
  RealEstateEconomics = "Real Estate Economics",
  ResourceEconomics = "Resource Economics",
  RiskManagementandInsurance = "Risk Management and Insurance",
  SocialistEconomics = "Socialist Economics",
  Socioeconomics = "Socioeconomics",
  Supplychainmanagement = "Supply chain management",
  TransportEconomics = "Transport Economics",
  WelfareEconomics = "Welfare Economics",
}

export enum EducationSubDisciplines {
  AdultEducation = "Adult Education",
  ComparativeEducation = "Comparative Education",
  CurriculumTheory = "Curriculum Theory",
  Didactics = "Didactics",
  EducationalAssessment = "Educational Assessment",
  EducationalLeadership = "Educational Leadership",
  EducationalManagement = "Educational Management",
  EducationalPolicy = "Educational Policy",
  EducationalTechnology = "Educational Technology",
  EducationalTheory = "Educational Theory",
  HigherEducation = "Higher Education",
  InternationalEducation = "International Education",
  LanguageEducation = "Language Education",
  MathematicsEducation = "Mathematics Education",
  PeaceEducation = "Peace Education",
  PedagogicTheory = "Pedagogic Theory",
  PrimaryEducation = "Primary Education",
  ScienceEducation = "Science Education",
  SecondaryEducation = "Secondary Education",
  SpecialEducation = "Special Education",
  TeacherEducation = "Teacher Education",
  TeachingMethods = "Teaching Methods",
  VocationalEducation = "Vocational Education",
  PreSchoolEducation = "Pre-school Education",
}

export enum EngineeringSubDisciplines {
  AcousticEngineering = "Acoustic Engineering",
  AeronauticalEngineering = "Aeronautical Engineering",
  AerospaceEngineering = "Aerospace Engineering",
  AgriculturalEngineering = "Agricultural Engineering",
  ArchitecturalEngineering = "Architectural Engineering",
  AutomotiveEngineering = "Automotive Engineering",
  AutomotiveSystemsEngineering = "Automotive Systems Engineering",
  Bioengineering = "Bioengineering",
  BiomedicalEngineering = "Biomedical Engineering",
  BiosystemsEngineering = "Biosystems Engineering",
  ChemicalEngineering = "Chemical Engineering",
  CivilEngineering = "Civil Engineering",
  CombatEngineering = "Combat Engineering",
  ComputerEngineering = "Computer Engineering",
  ControlSystemsEngineering = "Control Systems Engineering",
  ElectricalEngineering = "Electrical Engineering",
  ElectronicEngineering = "Electronic Engineering",
  EngineeringEducation = "Engineering Education",
  EngineeringPhysics = "Engineering Physics",
  EnvironmentalEngineering = "Environmental Engineering",
  FireSafetyEngineering = "Fire Safety Engineering",
  GameTheory = "Game Theory",
  IndustrialEngineering = "Industrial Engineering",
  InstrumentationEngineering = "Instrumentation Engineering",
  ManufacturingEngineering = "Manufacturing Engineering",
  MaterialsEngineering = "Materials Engineering",
  MechanicalEngineering = "Mechanical Engineering",
  MiningEngineering = "Mining Engineering",
  NavalEngineering = "Naval Engineering",
  NuclearEngineering = "Nuclear Engineering",
  OceanEngineering = "Ocean Engineering",
  OpticalEngineering = "Optical Engineering",
  PetroleumEngineering = "Petroleum Engineering",
  QualityAssuranceEgineering = "Quality Assurance Egineering",
  RailwayEngineering = "Railway Engineering",
  SafetyEngineering = "Safety Engineering",
  StructuralEngineering = "Structural Engineering",
  TelecommunicationsEngineering = "Telecommunications Engineering",
  TransportationEngineering = "Transportation Engineering",
}

export enum EntertainmentandArtsSubDisciplines {
  ArtsAdministration = "Arts Administration",
  PerformingArts = "Performing Arts",
  VisualArts = "Visual Arts",
}

export enum GeoscienceSubDisciplines {
  Cartography = "Cartography",
  Climatology = "Climatology",
  GaiaHypothesis = "Gaia Hypothesis",
  Geochemistry = "Geochemistry",
  GeodesyandSurveying = "Geodesy and Surveying",
  Geography = "Geography",
  Geoinformatics = "Geoinformatics",
  Geology = "Geology",
  Geomicrobiology = "Geomicrobiology",
  Geomorphology = "Geomorphology",
  Geostatistics = "Geostatistics",
  Hydrogeology = "Hydrogeology",
  Hydrology = "Hydrology",
  Meteorology = "Meteorology",
  Mineralogy = "Mineralogy",
  Oceanography = "Oceanography",
  Paleoclimatology = "Paleoclimatology",
  Paleontology = "Paleontology",
  Petrology = "Petrology",
  RemoteSensing = "Remote Sensing",
  Volcanology = "Volcanology",
}

export enum HistorySubDisciplines {
  HistoryofArt = "History of Art",
  HistoryofGeography = "History of Geography",
  HistoryofHistory = "History of History",
  HistoryofMathematics = "History of Mathematics",
  HistoryofPhilosophy = "History of Philosophy",
  HistoryofReligion = "History of Religion",
  HistoryofScience = "History of Science",
  Musicology = "Musicology",
}

export enum LawSubDisciplines {
  CivilLaw = "Civil Law",
  CriminalLaw = "Criminal Law",
  LegalFundaments = "Legal Fundaments",
  PublicLaw = "Public Law",
}

export enum LinguisticsSubDisciplines {
  CompositionStudies = "Composition Studies",
  ComputationalLinguistics = "Computational Linguistics",
  DiscourseAnalysis = "Discourse Analysis",
  HistoricalLinguistics = "Historical Linguistics",
  HistoryofLinguistics = "History of Linguistics",
  Interlinguistics = "Interlinguistics",
  LinguisticTypology = "Linguistic Typology",
  Morphology = "Morphology",
  Neurolinguistics = "Neurolinguistics",
  Philology = "Philology",
  Phonetics = "Phonetics",
  Phonology = "Phonology",
  Pragmatics = "Pragmatics",
  Psycholinguistics = "Psycholinguistics",
  Rhetoric = "Rhetoric",
  Semantics = "Semantics",
  Semiotics = "Semiotics",
  Sociolinguistics = "Sociolinguistics",
  Syntax = "Syntax",
}

export enum LiteratureSubDisciplines {
  EnglishLiterature = "English Literature",
  LiteraryTheory = "Literary Theory",
  WorldLiterature = "World Literature",
}

export enum MathematicsSubDisciplines {
  Algebra = "Algebra",
  Analysis = "Analysis",
  AppliedMathematics = "Applied Mathematics",
  GeometryandTopology = "Geometry and Topology",
  LogicandFoundationsofMathematics = "Logic and Foundations of Mathematics",
  NumberTheory = "Number Theory",
  ProbabilityTheory = "Probability Theory",
  Statistics = "Statistics",
}

export enum MedicineSubDisciplines {
  AddictionMedicine = "Addiction Medicine",
  Allergology = "Allergology",
  AlliedHealthScience = "Allied Health Science",
  Anaesthetics = "Anaesthetics",
  Andrology = "Andrology",
  BariatricSurgery = "Bariatric Surgery",
  Cardiology = "Cardiology",
  CardiothoracicSurgery = "Cardiothoracic Surgery",
  ClinicalChemistry = "Clinical Chemistry",
  ClinicalImmunology = "Clinical Immunology",
  ClinicalPharmacology = "Clinical Pharmacology",
  CounselingPsychology = "Counseling Psychology",
  DentalHygieneandEpidemiology = "Dental Hygiene and Epidemiology",
  DentalSurgery = "Dental Surgery",
  Dentistry = "Dentistry",
  Dermatology = "Dermatology",
  Diabetology = "Diabetology",
  DisasterMedicine = "Disaster Medicine",
  EmergencyMedicalCare = "Emergency Medical Care",
  EmergencyMedicine = "Emergency Medicine",
  EmergencyToxicology = "Emergency Toxicology",
  Epidemiology = "Epidemiology",
  ForensicScience = "Forensic Science",
  Gastroenterology = "Gastroenterology",
  GeneralPractice = "General Practice",
  GeneticEpidemiology = "Genetic Epidemiology",
  Geriatrics = "Geriatrics",
  Gynaecology = "Gynaecology",
  Hematology = "Hematology",
  Hepatology = "Hepatology",
  Implantology = "Implantology",
  InfectiousDiseases = "Infectious Diseases",
  InternalMedicine = "Internal Medicine",
  InternationalandHumanitarianMedicine = "International and Humanitarian Medicine",
  MedicalScienceNursing = "Medical Science Nursing",
  MedicalTechnology = "Medical Technology",
  Nephrology = "Nephrology",
  Neuroradiology = "Neuroradiology",
  Neurosurgery = "Neurosurgery",
  NursingScience = "Nursing Science",
  NutritionandDietetics = "Nutrition and Dietetics",
  NutritionalBiochemistry = "Nutritional Biochemistry",
  ObservationMedicine = "Observation Medicine",
  Obstetrics = "Obstetrics",
  Oncology = "Oncology",
  Ophtalmology = "Ophtalmology",
  Optometry = "Optometry",
  OralandMaxillofacialSurgery = "Oral and Maxillofacial Surgery",
  Orthodontics = "Orthodontics",
  OrthopedicSurgery = "Orthopedic Surgery",
  Otolaryngology = "Otolaryngology",
  Pathology = "Pathology",
  Pediatrics = "Pediatrics",
  Pedodontics = "Pedodontics",
  Periodontics = "Periodontics",
  Pharmacy = "Pharmacy",
  Physiotherapy = "Physiotherapy",
  PlasticSurgery = "Plastic Surgery",
  Podiatry = "Podiatry",
  PrimaryCare = "Primary Care",
  Prosthodontics = "Prosthodontics",
  Psychiatry = "Psychiatry",
  PsychosomaticsMedicine = "Psychosomatics Medicine",
  PublicHealth = "Public Health",
  Pulmonology = "Pulmonology",
  Radiology = "Radiology",
  RheabilitationMedicine = "Rheabilitation Medicine",
  RespiratoryMedicine = "Respiratory Medicine",
  RestorativeDentristryandEndodontics = "Restorative Dentristry and Endodontics",
  Rheumatology = "Rheumatology",
  SleepMedicine = "Sleep Medicine",
  SpeechandLanguagePathology = "Speech and Language Pathology",
  SportsMedicine = "Sports Medicine",
  Surgery = "Surgery",
  TacticalEmergencyMedicine = "Tactical Emergency Medicine",
  Toxicology = "Toxicology",
  TransfusionMedicine = "Transfusion Medicine",
  Traumatology = "Traumatology",
  Urology = "Urology",
  VeterinaryMedicine = "Veterinary Medicine",
  PreHospitalCare = "Pre-hospital Care",
}

export enum PhilosophySubDisciplines {
  Aesthetics = "Aesthetics",
  AppliedPhilosophy = "Applied Philosophy",
  Epistemology = "Epistemology",
  Ethics = "Ethics",
  Logic = "Logic",
  Metaphysics = "Metaphysics",
  PhilosophyofScience = "Philosophy of Science",
  SocialandPoliticalPhilosophy = "Social and Political Philosophy",
}

export enum PhysicsSubDisciplines {
  AcceleratorPhysics = "Accelerator Physics",
  Acoustics = "Acoustics",
  AtomicMolecularandOpticalPhysics = "Atomic, Molecular and Optical Physics",
  Biophysics = "Biophysics",
  ComputationalPhysics = "Computational Physics",
  CondensedMatterPhysics = "Condensed Matter Physics",
  Cosmology = "Cosmology",
  Cryogenics = "Cryogenics",
  Electromagnetism = "Electromagnetism",
  ElementaryParticlePhysics = "Elementary Particle Physics",
  ExperimentalPhysics = "Experimental Physics",
  FluidDynamics = "Fluid Dynamics",
  Geophysics = "Geophysics",
  MaterialsPhysics = "Materials Physics",
  MaterialsScience = "Materials Science",
  MathematicalPhysics = "Mathematical Physics",
  Mechanics = "Mechanics",
  MedicalPhysics = "Medical Physics",
  MolecularPhysics = "Molecular Physics",
  NewtonianDynamics = "Newtonian Dynamics",
  NuclearPhysics = "Nuclear Physics",
  Optics = "Optics",
  PlasmaPhysics = "Plasma Physics",
  QuantumPhysics = "Quantum Physics",
  SolidStatePhysics = "Solid State Physics",
  TheoreticalPhysics = "Theoretical Physics",
  Thermodynamics = "Thermodynamics",
  VehicleDynamics = "Vehicle Dynamics",
}

export enum PoliticalScienceSubDisciplines {
  ComparativeDemocratization = "Comparative Democratization",
  ComparativePolitics = "Comparative Politics",
  ConflictProcesses = "Conflict Processes",
  ElectionsPublicOpinionandVotingBehavior = "Elections, Public Opinion and Voting Behavior",
  FederalismandIntergovernmentalRelations = "Federalism and Intergovernmental Relations",
  ForeignPolicy = "Foreign Policy",
  FoundationsofPoliticalTheory = "Foundations of Political Theory",
  HealthPoliticsandPolicy = "Health Politics and Policy",
  HumanRights = "Human Rights",
  InformationTechnologyandPolitics = "Information Technology and Politics",
  InternationalHistoryandPolitics = "International History and Politics",
  InternationalRelations = "International Relations",
  InternationalSecurityandArmsControl = "International Security and Arms Control",
  LawandCourts = "Law and Courts",
  LegislativeStudies = "Legislative Studies",
  NationalPolitics = "National Politics",
  PoliticalCommunication = "Political Communication",
  PoliticalEconomy = "Political Economy",
  PoliticalMethodology = "Political Methodology",
  PoliticalNetworks = "Political Networks",
  PoliticalOrganizationsandParties = "Political Organizations and Parties",
  PoliticalPsychology = "Political Psychology",
  PoliticalScienceEducation = "Political Science Education",
  PoliticalTheory = "Political Theory",
  PoliticsandHistory = "Politics and History",
  PoliticsLiteratureandFilm = "Politics, Literature and Film",
  PresidencyResearch = "Presidency Research",
  PublicAdministration = "Public Administration",
  PublicPolicy = "Public Policy",
  RaceEthnicityandPolitics = "Race, Ethnicity and Politics",
  RepresentationandElectoralSystems = "Representation and Electoral Systems",
  ScienceTechnologyandEnvironmentalPolitics = "Science, Technology and Environmental Politics",
  StatePoliticsandPolicy = "State Politics and Policy",
  UrbanPolitics = "Urban Politics",
  WomenandPoliticsResearch = "Women and Politics Research",
  QualitativeandMultiMethodResearch = "Qualitative and Multi-method Research",
}

export enum PsychologySubDisciplines {
  AbnormalPsychology = "Abnormal Psychology",
  AppliedPsychology = "Applied Psychology",
  BehaviouralScience = "Behavioural Science",
  BiologicalPsychology = "Biological Psychology",
  ClinicalPsychology = "Clinical Psychology",
  CognitiveScience = "Cognitive Science",
  CommunityPsychology = "Community Psychology",
  DevelopmentalPsychology = "Developmental Psychology",
  DifferentialPsychology = "Differential Psychology",
  EducationalPsychology = "Educational Psychology",
  Emotion = "Emotion",
  EvolutionaryPsychology = "Evolutionary Psychology",
  ExperimentalPsychology = "Experimental Psychology",
  ForensicPsychology = "Forensic Psychology",
  HealthPsychology = "Health Psychology",
  IntrapersonalCommunications = "Intrapersonal Communications",
  LegalPsychology = "Legal Psychology",
  MediaPsychology = "Media Psychology",
  Neuropsychology = "Neuropsychology",
  OrganizationalPsychology = "Organizational Psychology",
  PersonalityPsychology = "Personality Psychology",
  PositivePsychology = "Positive Psychology",
  Psychoanalysis = "Psychoanalysis",
  Psychometrics = "Psychometrics",
  Psychophysics = "Psychophysics",
  QuantitativePsychology = "Quantitative Psychology",
  SocialPsychology = "Social Psychology",
  SportPsychology = "Sport Psychology",
}

export enum ReligiousStudiesSubDisciplines {
  AbrahamicReligions = "Abrahamic Religions",
  AtheismandHumanism = "Atheism and Humanism",
  ComparativeReligion = "Comparative Religion",
  IndianReligions = "Indian Religions",
  MythologyandFolklore = "Mythology and Folklore",
  OtherReligions = "Other Religions",
  TaoicReligions = "Taoic Religions",
}

export enum SocialScienceSubDisciplines {
  CommunicationandMedia = "Communication and Media",
  QualitativeSocialResearch = "Qualitative Social Research",
  QuantitativeSocialResearch = "Quantitative Social Research",
  SocialPolicy = "Social Policy",
  SocialStratification = "Social Stratification",
  SocialTheory = "Social Theory",
  Sociobiology = "Sociobiology",
  Sociocybernetics = "Sociocybernetics",
  SociologicalTheory = "Sociological Theory",
  UrbanRuralSociology = "Urban/Rural Sociology",
  VisualSociology = "Visual Sociology",
}

export enum SpaceScienceSubDisciplines {
  Astrobiology = "Astrobiology",
  Astronomy = "Astronomy",
  Astrophysics = "Astrophysics",
  ObservationalAstronomy = "Observational Astronomy",
}

export const disciplineMapping = {
  [PrimaryDiscipline.AgriculturalScience]: AgriculturalScienceSubDisciplines,
  [PrimaryDiscipline.Anthropology]: AnthropologySubDisciplines,
  [PrimaryDiscipline.Biology]: BiologySubDisciplines,
  [PrimaryDiscipline.Chemistry]: ChemistrySubDisciplines,
  [PrimaryDiscipline.ComputerScience]: ComputerScienceSubDisciplines,
  [PrimaryDiscipline.Design]: DesignSubDisciplines,
  [PrimaryDiscipline.Economics]: EconomicsSubDisciplines,
  [PrimaryDiscipline.Education]: EducationSubDisciplines,
  [PrimaryDiscipline.Engineering]: EngineeringSubDisciplines,
  [PrimaryDiscipline.EntertainmentandArts]: EntertainmentandArtsSubDisciplines,
  [PrimaryDiscipline.Geoscience]: GeoscienceSubDisciplines,
  [PrimaryDiscipline.History]: HistorySubDisciplines,
  [PrimaryDiscipline.Law]: LawSubDisciplines,
  [PrimaryDiscipline.Linguistics]: LinguisticsSubDisciplines,
  [PrimaryDiscipline.Literature]: LiteratureSubDisciplines,
  [PrimaryDiscipline.Mathematics]: MathematicsSubDisciplines,
  [PrimaryDiscipline.Medicine]: MedicineSubDisciplines,
  [PrimaryDiscipline.Philosophy]: PhilosophySubDisciplines,
  [PrimaryDiscipline.Physics]: PhysicsSubDisciplines,
  [PrimaryDiscipline.PoliticalScience]: PoliticalScienceSubDisciplines,
  [PrimaryDiscipline.Psychology]: PsychologySubDisciplines,
  [PrimaryDiscipline.ReligiousStudies]: ReligiousStudiesSubDisciplines,
  [PrimaryDiscipline.SocialScience]: SocialScienceSubDisciplines,
  [PrimaryDiscipline.SpaceScience]: SpaceScienceSubDisciplines,
};
