import { UserReq } from "../../../../shared-types/userData";

export const getTextFieldsConfig = (user: UserReq) => [
  {
    label: "login_information_mail",
    placeholder: "loing_mail_placeholder",
    type: "email",
    value: user.email,
    textfield: "email",
    required: true,
  },
  {
    label: "login_password",
    placeholder: "login_password_placeholder",
    type: "password",
    value: user.password,
    textfield: "password",
    required: true,
  },
  {
    label: "general_information_first_name",
    placeholder: "general_information_first_name_placeholder",
    type: "text",
    value: user.firstName,
    textfield: "firstName",
    required: true,
  },
  {
    label: "general_information_last_name",
    placeholder: "general_information_last_name_placeholder",
    type: "text",
    value: user.lastName,
    textfield: "lastName",
    required: true,
  },
  {
    label: "general_information_organization_name",
    placeholder: "",
    type: "text",
    value: user.organizationName,
    textfield: "organizationName",
    required: true,
    professionalLayout: true,
  },
  {
    label: "general_information_type_of_organization",
    placeholder: "",
    type: "text",
    value: user.typeOfOrganizationSpecific,
    textfield: "typeOfOrganizationSpecific",
    required: true,
    professionalLayout: true,
  },
  {
    label: "general_information_institution",
    placeholder: "",
    type: "text",
    value: user.institution,
    textfield: "institution",
    researcherLayout: true,
  },
  {
    label: "general_information_laborayory_name",
    placeholder: "",
    type: "text",
    value: user.typeOfOrganizationSpecific,
    textfield: "typeOfOrganizationSpecific",
    researcherLayout: true,
  },
  {
    label: "general_information_verify_profile",
    placeholder:
      "general_information_verify_profile_placeholder",
    type: "text",
    value: user.profileVerificationInfo,
    textfield: "profileVerificationInfo",
    multiline: true,
    researcherLayout: true,
    required: true,
  },
];
