import { User } from "../../../../shared-types/userData";

export const getTextFieldsConfig = (user: User) => [
  {
    label: "First name",
    placeholder: "Enter first name",
    type: "text",
    value: user.firstName,
    field: "firstName",
    required: true,
  },
  {
    label: "Last name",
    placeholder: "Enter last name",
    type: "text",
    value: user.lastName,
    field: "lastName",
    required: true,
  },
  {
    label: "Mail address",
    placeholder: "Enter mail address",
    type: "email",
    value: user.email,
    field: "email",
    required: true,
  },
  {
    label: "Password",
    placeholder: "Enter password",
    type: "password",
    value: user.password,
    field: "password",
    required: true,
  },
  {
    label: "Organization name",
    placeholder: "",
    type: "text",
    value: user.organizationName,
    field: "organizationName",
    required: true,
  },
  {
    label: "Institution (if relevant)",
    placeholder: "",
    type: "text",
    value: user.institution,
    field: "institution",
  },
  {
    label: "Address",
    placeholder: "",
    type: "text",
    value: user.address,
    field: "address",
    required: true,
  },
  {
    label: "City",
    placeholder: "",
    type: "text",
    value: user.city,
    field: "city",
    required: true,
  },
  {
    label: "Country",
    placeholder: "",
    type: "text",
    value: user.country,
    field: "country",
    required: true,
  },
  {
    label: "Describe in a few words your professional activity",
    placeholder: "",
    type: "text",
    value: user.description,
    field: "description",
  },
];
