import { UserReq } from "../../../../shared-types/userData";

export const getTextFieldsConfig = (user: UserReq) => [
  {
    label: "Mail address",
    placeholder: "Enter mail address",
    type: "email",
    value: user.email,
    textfield: "email",
    required: true,
  },
  {
    label: "Password",
    placeholder: "Enter password",
    type: "password",
    value: user.password,
    textfield: "password",
    required: true,
  },
  {
    label: "First name",
    placeholder: "Enter first name",
    type: "text",
    value: user.firstName,
    textfield: "firstName",
    required: true,
  },
  {
    label: "Last name",
    placeholder: "Enter last name",
    type: "text",
    value: user.lastName,
    textfield: "lastName",
    required: true,
  },
  {
    label: "Country",
    placeholder: "",
    type: "text",
    value: user.country,
    textfield: "country",
    required: true,
    researcherLayout: true,
  },
  {
    label: "Organization name",
    placeholder: "",
    type: "text",
    value: user.organizationName,
    textfield: "organizationName",
    required: true,
    professionalLayout: true,
  },
  {
    label: "Type of organization",
    placeholder: "",
    type: "text",
    value: user.typeOfOrganizationSpecific,
    textfield: "typeOfOrganizationSpecific",
    required: true,
    professionalLayout: true,
  },
  {
    label: "Country",
    placeholder: "",
    type: "text",
    value: user.country,
    textfield: "country",
    required: true,
    professionalLayout: true,
  },
  {
    label: "Institution (if relevant)",
    placeholder: "",
    type: "text",
    value: user.institution,
    textfield: "institution",
    researcherLayout: true,
  },
  {
    label: "Laboratory/department or organization name",
    placeholder: "",
    type: "text",
    value: user.typeOfOrganizationSpecific,
    textfield: "typeOfOrganizationSpecific",
    researcherLayout: true,
  },
  {
    label: "Give us any information in order to verify your profile",
    placeholder:
      "ORCID iD, ResearchGate or LinkedIn account, link to articles published, link to your website laboratory/department where you appear ...",
    type: "text",
    value: user.profileVerificationInfo,
    textfield: "profileVerificationInfo",
    multiline: true,
    researcherLayout: true,
    required: true,
  },
];
